
using System.Linq;
using System.Collections.Generic;
using DndClassJson;
using sharpAngleTemplate.Repositories;
using DndClassJson;
using sharpAngleTemplate.models.DTO;
using sharpAngleTemplate.models.entities; // Add missing using directive

namespace sharpAngleTemplate
{
    public static class ClassMappers
    {
        public static ClassDTO ClassJsonToDto(this The5EClasses jsonClass)
        {
            return new ClassDTO(){
                Name = jsonClass.Name,
                Hit_Die = (int)jsonClass.HitDie,
                Proficiency_Choices = jsonClass.ProficiencyChoices,
                Saving_Throws = jsonClass.SavingThrows,
                Skills = new SkillDTO(){
                    Amount = (int)jsonClass.Skills.Amount,
                    Skills = jsonClass.Skills.SkillsSkills,
                },
                Starting_Equipment = jsonClass.StartingEquipment,
                Class_Levels = jsonClass.ClassLevels.Select((level, index) => new ClassLevelDTO(){
                    Level = index + 1,
                    ProficiencyBonus = (int)level.ProficiencyBonus,
                    Features = level.Features,
                    Spellcasting = new ClassLevelSpellcastingDTO(){
                        CantripsKnown = (int)level.Spellcasting.CantripsKnown,
                        InvocationsKnown = level.Spellcasting.InvocationsKnown.ToString(),
                        SpellSlotLevel = level.Spellcasting.SlotLevel,
                    },
                    Other = new models.DTO.Other(){
                        Rage = level.Other.Rage.Content.Stringify(),
                        UnarmoredDefense = level.Other.UnarmoredDefense,
                        RecklessAttack = level.Other.RecklessAttack,
                        DangerSense = level.Other.DangerSense.Content,
                        PrimalPath = level.Other.PrimalPath,
                        AbilityScoreImprovement = level.Other.AbilityScoreImprovement,
                        ExtraAttack = level.Other.ExtraAttack.ToString(),
                        FastMovement = level.Other.FastMovement,
                        PathFeature = level.Other.PathFeature?.ToString(),
                        FeralInstinct = level.Other.FeralInstinct.Content,
                        BrutalCritical = level.Other.BrutalCritical.Content,
                        Relentless = level.Other.Relentless.Content,
                        PersistentRage = level.Other.PersistentRage,
                        IndomitableMight = level.Other.IndomitableMight,
                        PrimalChampion = level.Other.PrimalChampion,
                        JackOfAllTrades = level.Other.JackOfAllTrades,
                        FontOfInspiration = level.Other.FontOfInspiration,
                        BardCollege = level.Other.BardCollege,
                        Countercharm = level.Other.Countercharm,
                        MagicalSecrets = level.Other.MagicalSecrets,
                        Expertise = level.Other.Expertise.Content,
                        SuperiorInspiration = level.Other.SuperiorInspiration,
                        DivineIntervention = level.Other.DivineIntervention.Content,
                        DruidCircle = level.Other.DruidCircle,
                        TimelessBody = level.Other.TimelessBody,
                        BeastSpells = level.Other.BeastSpells,
                        Archdruid = level.Other.Archdruid.Content,
                        SecondWind = level.Other.SecondWind,
                        ActionSurge = level.Other.ActionSurge.Content,
                        MartialArchetypeFeature = level.Other.MartialArchetypeFeature,
                        Indomitable = level.Other.Indomitable,
                        UnarmoredMovement = level.Other.UnarmoredMovement.Content,
                        MonasticTradition = level.Other.MonasticTradition,
                        DeflectMissiles = level.Other.DeflectMissiles.Content,
                        SlowFall = level.Other.SlowFall,
                        StunningStrike = level.Other.StunningStrike,
                        KiEmpoweredStrikes = level.Other.KiEmpoweredStrikes,
                        Evasion = level.Other.Evasion,
                        StillnessOfMind = level.Other.StillnessOfMind,
                        UnarmoredMovementImprovement = level.Other.UnarmoredMovementImprovement.Content,
                        PurityOfBody = level.Other.PurityOfBody,
                        TongueOfTheSunAndMoon = level.Other.TongueOfTheSunAndMoon,
                        DiamondSoul = level.Other.DiamondSoul.Content,
                        EmptyBody = level.Other.EmptyBody.Content,
                        DivineSense = level.Other.DivineSense.Content,
                        LayOnHands = level.Other.LayOnHands.Content,
                        DivineSmite = level.Other.DivineSmite,
                        DivineHealth = level.Other.DivineHealth,
                        AuraOfProtection = level.Other.AuraOfProtection.Content,
                        AuraOfCourage = level.Other.AuraOfCourage.Content,
                        ImprovedDivineSmite = level.Other.ImprovedDivineSmite,
                        CleansingTouch = level.Other.CleansingTouch.Content,
                        AuraImprovements = level.Other.AuraImprovements.Content,
                        AuraOfDevotion = level.Other.AuraOfDevotion.Content,
                        FavoredEnemy = level.Other.FavoredEnemy.Content,
                        RangerArchetype = level.Other.RangerArchetype,
                        FavoredEnemyAndNaturalExplorerImprovements = level.Other.FavoredEnemyAndNaturalExplorerImprovements.Content,
                        LandSStride = level.Other.LandSStride.Content,
                        NaturalExplorerImprovement = level.Other.NaturalExplorerImprovement.Stringify(),
                        HideInPlainSight = level.Other.HideInPlainSight.Content,
                        FavoredEnemyImprovement = level.Other.FavoredEnemyImprovement.Content,
                        Vanish = level.Other.Vanish,
                        FeralSenses = level.Other.FeralSenses.Content,
                        FoeSlayer = level.Other.FoeSlayer,
                        ThievesCant = level.Other.ThievesCant.Content,
                        CunningAction = level.Other.CunningAction,
                        RoguishArchetype = level.Other.RoguishArchetype,
                        SneakAttack = level.Other.SneakAttack,
                        UncannyDodge = level.Other.UncannyDodge,
                        ReliableTalent = level.Other.ReliableTalent,
                        Blindsense = level.Other.Blindsense,
                        SlipperyMind = level.Other.SlipperyMind,
                        Elusive = level.Other.Elusive,
                        StrokeOfLuck = level.Other.StrokeOfLuck.Content,
                        SorcerousOrigin = level.Other.SorcerousOrigin.Content,
                        SorcerousRestoration = level.Other.SorcerousRestoration,
                        OtherworldlyPatron = level.Other.OtherworldlyPatron,
                        EldritchInvocations = level.Other.EldritchInvocations.Content,
                        MysticArcanum = level.Other.MysticArcanum.Content,
                        EldritchMaster = level.Other.EldritchMaster,
                        ArcaneRecovery = level.Other.ArcaneRecovery.Content,
                        ArcaneTradition = level.Other.ArcaneTradition.Content,
                        SpellMastery = level.Other.SpellMastery.Content,
                        SignatureSpells = level.Other.SignatureSpells.Content,
                        Spellcasting = new sharpAngleTemplate.models.DTO.Spellcasting(){
                            Content = level.Other.Spellcasting.Content.String,
                            Cantrips = level.Other.Spellcasting.Cantrips,
                            SpellSlots = level.Other.Spellcasting.SpellSlots.Content,
                            SpellsKnownOf1StLevelAndHigher = level.Other.Spellcasting.SpellsKnownOf1StLevelAndHigher.Content,
                            SpellcastingAbility = level.Other.Spellcasting.SpellcastingAbility.Content,
                            RitualCasting = level.Other.Spellcasting.RitualCasting,
                            SpellcastingFocus = level.Other.Spellcasting.SpellcastingFocus,
                            PreparingAndCastingSpells = level.Other.Spellcasting.PreparingAndCastingSpells.Content,
                            Spellbook = level.Other.Spellcasting.Spellbook,
                            LearningSpellsOf1StLevelAndHigher = level.Other.Spellcasting.LearningSpellsOf1StLevelAndHigher,
                        },
                        DivineDomain = level.Other.DivineDomain.Stringify(),
                        DestroyUndead = level.Other.DestroyUndead.Content,
                        ChannalDivinity = level.Other.ChannalDivinity.Content.Stringify(),
                        WildShape = level.Other.WildShape.Content.Stringify(),
                        FightingStyle = level.Other.FightingStyle.Content.Stringify(),
                        MartialArts = level.Other.MartialArts.Content.Stringify(),
                        NaturalExplorer = level.Other.NaturalExplorer.Content.Stringify(),
                        Ki = level.Other.Ki.Content.Stringify(),
                        MonasticTraditionFeature = level.Other.MonasticTraditionFeature?.Stringify(),
                        SacredOath = level.Other.SacredOath.Content.Stringify(),
                        SacredOathFeature = level.Other.SacredOathFeature?.Stringify(),
                        RangerArchetypeFeature = level.Other.RangerArchetypeFeature?.Stringify(),
                        RoguishArchetypeFeature = level.Other.RoguishArchetypeFeature?.Stringify(),
                        FontOfMagic = level.Other.FontOfMagic.Content.Stringify(),
                        Metamagic = level.Other.Metamagic.Content.Stringify(),
                        SorcerousOriginFeature = level.Other.SorcerousOriginFeature?.Stringify(),
                        PactBoon = level.Other.PactBoon.Content.Stringify(),
                        PactMagic = level.Other.PactMagic.Content.Stringify(),
                        ArcaneTraditionFeature = level.Other.ArcaneTraditionFeature?.Stringify(),
                    }
                }).ToList(),
            };
            }
        }
    
}
