name: CI & Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  packages: write  # needed for GHCR push
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        dotnet-version: ["8.0.x"] 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      # Restore .NET dependencies
      - name: Restore .NET dependencies
        run: dotnet restore

      # Build .NET project
      - name: Build .NET project
        run: dotnet build --configuration Release --no-restore

      # Test .NET project
      - name: Test .NET project
        run: dotnet test --no-build --verbosity normal

      # Setup Node.js
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install NPM dependencies
      - name: Install NPM dependencies
        working-directory: ./client
        run: npm ci

      # Build SolidJS project
      - name: Build SolidJS project
        working-directory: ./client
        run: npm run build

      # Test SolidJS project
      # - name: Test SolidJS project
      #   working-directory: ./client
      #   run: npm run test

      # Validate Docker image builds (no push)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/serving-solid-characters:latest
            ghcr.io/${{ github.repository_owner }}/serving-solid-characters:${{ github.sha }}
          build-args: |
            BUILD_CONFIGURATION=Release
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (for compose & scripts)
        uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.LINODE_SSH_KEY }}

      - name: Copy compose file & scripts
        run: |
          scp -o StrictHostKeyChecking=no docker-compose.prod.yml ${{ secrets.LINODE_USER }}@${{ secrets.LINODE_HOST }}:/opt/serving-solid-characters/docker-compose.yml
          scp -o StrictHostKeyChecking=no scripts/deploy.sh ${{ secrets.LINODE_USER }}@${{ secrets.LINODE_HOST }}:/opt/serving-solid-characters/deploy.sh

      - name: Deploy over SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.LINODE_USER }}@${{ secrets.LINODE_HOST }} 'chmod +x /opt/serving-solid-characters/deploy.sh && IMAGE_TAG=latest /opt/serving-solid-characters/deploy.sh'

      # Optional: Push Docker Image to Registry
      #- name: Login to Docker Registry
      #  if: github.event_name == 'push' # Only push on commits to main
      #  uses: docker/login-action@v2
      #  with:
      #    registry: docker.io
      #    username: ${{ secrets.DOCKER_USERNAME }}
      #    password: ${{ secrets.DOCKER_PASSWORD }}

      #- name: Push Docker Image
      #  if: github.event_name == 'push' # Only push on commits to main
      #  run: docker push your-docker-image:${{ github.sha }}
