name: .NET and SolidJS CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        dotnet-version: ["8.0.x"] 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      # Restore .NET dependencies
      - name: Restore .NET dependencies
        run: dotnet restore

      # Build .NET project
      - name: Build .NET project
        run: dotnet build --configuration Release --no-restore

      # Test .NET project
      - name: Test .NET project
        run: dotnet test --no-build --verbosity normal

      # Setup Node.js
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install NPM dependencies
      - name: Install NPM dependencies
        working-directory: ./client
        run: npm ci

      # Build SolidJS project
      - name: Build SolidJS project
        working-directory: ./client
        run: npm run build

      # Test SolidJS project
      # - name: Test SolidJS project
      #   working-directory: ./client
      #   run: npm run test

      # Validate Docker image builds (no push)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (test only)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: false
          tags: serving-solid-characters:test-${{ github.sha }}
          build-args: |
            BUILD_CONFIGURATION=Release
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Optional: Push Docker Image to Registry
      #- name: Login to Docker Registry
      #  if: github.event_name == 'push' # Only push on commits to main
      #  uses: docker/login-action@v2
      #  with:
      #    registry: docker.io
      #    username: ${{ secrets.DOCKER_USERNAME }}
      #    password: ${{ secrets.DOCKER_PASSWORD }}

      #- name: Push Docker Image
      #  if: github.event_name == 'push' # Only push on commits to main
      #  run: docker push your-docker-image:${{ github.sha }}
